@baseUrl = http://localhost:3001/api/v2/users


### GET users
GET {{baseUrl}}


### POST user
POST {{baseUrl}}
Content-Type: application/json

{
  "username": "Ittikorn",
  "email": "ittikorn@example.com",
  "password": "pass123",
  "role": "user"
}


### PUT user
PUT {{baseUrl}}/ใส่_MongoDB_ID_ตรงนี้
Content-Type: application/json

{
  "username": "Ittikorn Updated",
  "email": "ittikorn.updated@example.com",
  "role": "admin"
}


### DELETE user
DELETE {{baseUrl}}/ใส่_MongoDB_ID_ตรงนี้